name: smart_aquarium
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fpdart: ^1.1.0
  localization: ^2.1.1
  lottie: ^3.1.2
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/animations/
    - lib/assets/fonts/
    - lib/assets/i18n/
    - lib/assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: lib/assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/montserrat/Montserrat-Italic.ttf
          style: italic
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/poppins/Poppins-Regular.ttf
        - asset: lib/assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
